# Generated by Django 5.0.6 on 2024-05-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodTruck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationid', models.CharField(max_length=100)),
                ('Applicant', models.CharField(max_length=255)),
                ('FacilityType', models.CharField(max_length=100)),
                ('cnn', models.CharField(max_length=100)),
                ('LocationDescription', models.CharField(max_length=255)),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
            ],
        ),
    ]
