# Generated by Django 5.0.6 on 2024-05-15 15:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtrucks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtrucks',
            name='Address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='foodtrucks',
            name='Approved',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='foodtrucks',
            name='ExpirationDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='foodtrucks',
            name='FirePreventionDistricts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='foodtrucks',
            name='FoodItems',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='foodtrucks',
            name='Location',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='foodtrucks',
            name='NOISent',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='foodtrucks',
            name='Neighborhoods_old',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='foodtrucks',
            name='PoliceDistricts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='foodtrucks',
            name='PriorPermit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='foodtrucks',
            name='Received',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='foodtrucks',
            name='Schedule',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='foodtrucks',
            name='Status',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='foodtrucks',
            name='SupervisorDistricts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='foodtrucks',
            name='X',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='foodtrucks',
            name='Y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='foodtrucks',
            name='ZipCodes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='foodtrucks',
            name='block',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='foodtrucks',
            name='blocklot',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='foodtrucks',
            name='dayshours',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='foodtrucks',
            name='lot',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='foodtrucks',
            name='permit',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='foodtrucks',
            name='Applicant',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='foodtrucks',
            name='FacilityType',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='foodtrucks',
            name='Latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='foodtrucks',
            name='LocationDescription',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='foodtrucks',
            name='Longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='foodtrucks',
            name='cnn',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='foodtrucks',
            name='locationid',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
