# Generated by Django 5.0.6 on 2024-05-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtrucks', '0002_foodtruck_address_foodtruck_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtrucks',
            name='Approved',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='foodtrucks',
            name='ExpirationDate',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='foodtrucks',
            name='Received',
            field=models.CharField(default='', max_length=255),
        ),
    ]
