# Generated by Django 5.0.6 on 2024-05-15 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodtrucks', '0006_alter_foodtruck_address_alter_foodtruck_applicant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodtrucks',
            old_name='Latitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='foodtrucks',
            old_name='Longitude',
            new_name='longitude',
        ),
    ]
